import type {
  ActivityField,
  ActivityType,
  BFASScores,
  BFASTraitDefinition,
  Build,
  EmploymentStatus,
  Gender,
  PersonalityScores,
  PersonalityTrait,
  PersonalityType,
} from "./index.js"

export const GENDERS: Gender[] = [
  "Male",
  "Female",
  "Non-binary",
  "Prefer not to say",
]

export const BUILDS: Build[] = ["Slim", "Athletic", "Average", "Heavy"]

export const EMPLOYMENT_STATUSES: EmploymentStatus[] = [
  "Student",
  "Employed",
  "Unemployed",
  "Retired",
]

export const ACTIVITY_TYPES: ActivityType[] = [
  "Creative",
  "Artistic",
  "Constructive",
  "Expressive",
  "Performative",

  "Intellectual",
  "Analytical",
  "Educational",
  "Reflective",

  "Active",
  "Physical",
  "Skill-based",
  "Competitive",

  "Adventurous",
  "Outdoorsy",
  "Exploratory",
  "Experimental",

  "Social",
  "Collaborative",
  "Leadership",
  "Community-oriented",

  "Professional",
  "Goal-oriented",
  "Disciplined",
  "Strategic",

  "Mindful",
  "Therapeutic",
  "Emotional",
]

export const ACTIVITY_FIELDS: ActivityField[] = [
  "Music",
  "Art",
  "Writing",
  "Photography",
  "Film",
  "Theater",
  "Dance",

  "Coding",
  "Technology",
  "Science",
  "Astronomy",
  "Engineering",

  "Cars",
  "Motorcycles",
  "Aviation",

  "Fitness",
  "Sports",
  "Martial Arts",
  "Cycling",
  "Running",
  "Climbing",
  "Hiking",

  "Gaming",
  "Board Games",

  "Cooking",
  "Coffee",
  "Fashion",

  "Travel",
  "Nature",
  "Camping",

  "Psychology",
  "Philosophy",
  "History",
  "Language",

  "Business",
  "Finance",
  "Leadership",

  "Meditation",
  "Wellness",

  "Education",
  "Community",
  "Volunteering",

  "DIY",
  "Home Design",
  "Collecting",
]

export const PERSONALITY_TRAITS: PersonalityTrait[] = [
  {
    key: "Openness",
    label: "Openness",
    description:
      "How much you enjoy new ideas, abstract thinking, and unfamiliar experiences.",
    lowLabel: "Practical",
    highLabel: "Curious",
  },
  {
    key: "Conscientiousness",
    label: "Conscientiousness",
    description:
      "How structured and goal-driven you are versus flexible and spontaneous.",
    lowLabel: "Spontaneous",
    highLabel: "Disciplined",
  },
  {
    key: "Extraversion",
    label: "Extraversion",
    description:
      "How energised you feel around other people compared to time alone.",
    lowLabel: "Reserved",
    highLabel: "Outgoing",
  },
  {
    key: "Agreeableness",
    label: "Agreeableness",
    description:
      "How much you prioritise harmony and cooperation versus directness and competition.",
    lowLabel: "Direct",
    highLabel: "Cooperative",
  },
  {
    key: "Neuroticism",
    label: "Neuroticism",
    description:
      "How strongly you experience stress and emotional ups and downs.",
    lowLabel: "Calm",
    highLabel: "Sensitive",
  },
]

export const DEFAULT_PERSONALITY_SCORES: PersonalityScores = {
  Openness: 50,
  Conscientiousness: 50,
  Extraversion: 50,
  Agreeableness: 50,
  Neuroticism: 50,
}

const PERSONALITY_TRAIT_BY_KEY = Object.fromEntries(
  PERSONALITY_TRAITS.map((trait) => [trait.key, trait]),
) as Record<PersonalityType, PersonalityTrait>

export const BFAS_TRAITS: BFASTraitDefinition[] = [
  {
    key: "Openness",
    label: "Openness",
    description: "How much you seek out novel experiences, art, and sensory beauty.",
    lowLabel: "Conventional",
    highLabel: "Imaginative",
    parent: PERSONALITY_TRAIT_BY_KEY.Openness,
  },
  {
    key: "Intellect",
    label: "Intellect",
    description: "How drawn you are to abstract ideas, puzzles, and intellectual debate.",
    lowLabel: "Concrete",
    highLabel: "Analytical",
    parent: PERSONALITY_TRAIT_BY_KEY.Openness,
  },
  {
    key: "Industriousness",
    label: "Industriousness",
    description: "How hard-working and persistent you are when pursuing goals.",
    lowLabel: "Easygoing",
    highLabel: "Driven",
    parent: PERSONALITY_TRAIT_BY_KEY.Conscientiousness,
  },
  {
    key: "Orderliness",
    label: "Orderliness",
    description: "How much you prefer structure, routine, and keeping things tidy.",
    lowLabel: "Flexible",
    highLabel: "Organised",
    parent: PERSONALITY_TRAIT_BY_KEY.Conscientiousness,
  },
  {
    key: "Enthusiasm",
    label: "Enthusiasm",
    description: "How exuberant, talkative, and positive you are around others.",
    lowLabel: "Quiet",
    highLabel: "Enthusiastic",
    parent: PERSONALITY_TRAIT_BY_KEY.Extraversion,
  },
  {
    key: "Assertiveness",
    label: "Assertiveness",
    description: "How confidently you take charge, speak up, and lead.",
    lowLabel: "Compliant",
    highLabel: "Assertive",
    parent: PERSONALITY_TRAIT_BY_KEY.Extraversion,
  },
  {
    key: "Compassion",
    label: "Compassion",
    description: "How empathetic and caring you are towards others' feelings.",
    lowLabel: "Detached",
    highLabel: "Empathetic",
    parent: PERSONALITY_TRAIT_BY_KEY.Agreeableness,
  },
  {
    key: "Politeness",
    label: "Politeness",
    description: "How much you defer to others, avoid conflict, and follow social norms.",
    lowLabel: "Blunt",
    highLabel: "Considerate",
    parent: PERSONALITY_TRAIT_BY_KEY.Agreeableness,
  },
  {
    key: "Volatility",
    label: "Volatility",
    description: "How quickly your mood shifts and how intensely you react to stress.",
    lowLabel: "Even-keeled",
    highLabel: "Reactive",
    parent: PERSONALITY_TRAIT_BY_KEY.Neuroticism,
  },
  {
    key: "Withdrawal",
    label: "Withdrawal",
    description: "How prone you are to anxiety, self-doubt, and pulling away from others.",
    lowLabel: "Confident",
    highLabel: "Withdrawn",
    parent: PERSONALITY_TRAIT_BY_KEY.Neuroticism,
  },
]

export const BFAS_PARENT_LABELS: Record<PersonalityType, string> = {
  Openness: "Openness to Experience",
  Conscientiousness: "Conscientiousness",
  Extraversion: "Extraversion",
  Agreeableness: "Agreeableness",
  Neuroticism: "Neuroticism",
}

export const DEFAULT_BFAS_SCORES: BFASScores = {
  Openness: 50,
  Intellect: 50,
  Industriousness: 50,
  Orderliness: 50,
  Enthusiasm: 50,
  Assertiveness: 50,
  Compassion: 50,
  Politeness: 50,
  Volatility: 50,
  Withdrawal: 50,
}

export const ACTIVITY_TYPE_BFAS_MAPPING: Record<ActivityType, Partial<BFASScores>> = {
  Creative: {
    Openness: 90,
    Intellect: 50,
    Industriousness: 50,
    Orderliness: 30,
    Enthusiasm: 50,
    Assertiveness: 40,
    Compassion: 60,
    Politeness: 50,
    Volatility: 60,
    Withdrawal: 60,
  },
  Artistic: {
    Openness: 80,
    Intellect: 40,
    Industriousness: 40,
    Orderliness: 20,
    Enthusiasm: 60,
    Assertiveness: 30,
    Compassion: 70,
    Politeness: 50,
    Volatility: 70,
    Withdrawal: 70,
  },
  Constructive: {
    Openness: 60,
    Intellect: 50,
    Industriousness: 70,
    Orderliness: 60,
    Enthusiasm: 50,
    Assertiveness: 50,
    Compassion: 50,
    Politeness: 50,
    Volatility: 50,
    Withdrawal: 50,
  },
  Expressive: {
    Openness: 85,
    Intellect: 40,
    Industriousness: 45,
    Orderliness: 25,
    Enthusiasm: 70,
    Assertiveness: 50,
    Compassion: 60,
    Politeness: 50,
    Volatility: 65,
    Withdrawal: 60,
  },
  Performative: {
    Openness: 70,
    Intellect: 40,
    Industriousness: 50,
    Orderliness: 30,
    Enthusiasm: 80,
    Assertiveness: 70,
    Compassion: 50,
    Politeness: 40,
    Volatility: 60,
    Withdrawal: 50,
  },

  Intellectual: {
    Openness: 80,
    Intellect: 80,
    Industriousness: 60,
    Orderliness: 50,
    Enthusiasm: 40,
    Assertiveness: 50,
    Compassion: 40,
    Politeness: 40,
    Volatility: 40,
    Withdrawal: 50,
  },
  Analytical: {
    Openness: 60,
    Intellect: 80,
    Industriousness: 60,
    Orderliness: 70,
    Enthusiasm: 40,
    Assertiveness: 50,
    Compassion: 40,
    Politeness: 40,
    Volatility: 35,
    Withdrawal: 45,
  },
  Educational: {
    Openness: 60,
    Intellect: 70,
    Industriousness: 50,
    Orderliness: 60,
    Enthusiasm: 50,
    Assertiveness: 40,
    Compassion: 70,
    Politeness: 60,
    Volatility: 40,
    Withdrawal: 40,
  },
  Reflective: {
    Openness: 70,
    Intellect: 60,
    Industriousness: 40,
    Orderliness: 40,
    Enthusiasm: 30,
    Assertiveness: 30,
    Compassion: 50,
    Politeness: 50,
    Volatility: 40,
    Withdrawal: 60,
  },

  Active: {
    Openness: 50,
    Intellect: 30,
    Industriousness: 60,
    Orderliness: 50,
    Enthusiasm: 70,
    Assertiveness: 60,
    Compassion: 50,
    Politeness: 40,
    Volatility: 50,
    Withdrawal: 40,
  },
  Physical: {
    Openness: 40,
    Intellect: 30,
    Industriousness: 60,
    Orderliness: 50,
    Enthusiasm: 60,
    Assertiveness: 60,
    Compassion: 40,
    Politeness: 40,
    Volatility: 50,
    Withdrawal: 40,
  },
  "Skill-based": {
    Openness: 50,
    Intellect: 50,
    Industriousness: 70,
    Orderliness: 70,
    Enthusiasm: 50,
    Assertiveness: 50,
    Compassion: 40,
    Politeness: 50,
    Volatility: 40,
    Withdrawal: 40,
  },
  Competitive: {
    Openness: 40,
    Intellect: 50,
    Industriousness: 70,
    Orderliness: 60,
    Enthusiasm: 70,
    Assertiveness: 80,
    Compassion: 30,
    Politeness: 30,
    Volatility: 60,
    Withdrawal: 40,
  },

  Adventurous: {
    Openness: 85,
    Intellect: 50,
    Industriousness: 50,
    Orderliness: 30,
    Enthusiasm: 70,
    Assertiveness: 60,
    Compassion: 50,
    Politeness: 50,
    Volatility: 65,
    Withdrawal: 50,
  },
  Outdoorsy: {
    Openness: 60,
    Intellect: 40,
    Industriousness: 50,
    Orderliness: 50,
    Enthusiasm: 60,
    Assertiveness: 50,
    Compassion: 60,
    Politeness: 50,
    Volatility: 50,
    Withdrawal: 45,
  },
  Exploratory: {
    Openness: 80,
    Intellect: 60,
    Industriousness: 50,
    Orderliness: 40,
    Enthusiasm: 60,
    Assertiveness: 50,
    Compassion: 50,
    Politeness: 50,
    Volatility: 60,
    Withdrawal: 50,
  },
  Experimental: {
    Openness: 90,
    Intellect: 70,
    Industriousness: 50,
    Orderliness: 20,
    Enthusiasm: 60,
    Assertiveness: 50,
    Compassion: 50,
    Politeness: 40,
    Volatility: 70,
    Withdrawal: 60,
  },

  Social: {
    Openness: 50,
    Intellect: 40,
    Industriousness: 40,
    Orderliness: 40,
    Enthusiasm: 80,
    Assertiveness: 50,
    Compassion: 70,
    Politeness: 60,
    Volatility: 50,
    Withdrawal: 40,
  },
  Collaborative: {
    Openness: 50,
    Intellect: 50,
    Industriousness: 60,
    Orderliness: 50,
    Enthusiasm: 70,
    Assertiveness: 50,
    Compassion: 80,
    Politeness: 70,
    Volatility: 40,
    Withdrawal: 40,
  },
  Leadership: {
    Openness: 60,
    Intellect: 50,
    Industriousness: 70,
    Orderliness: 60,
    Enthusiasm: 70,
    Assertiveness: 80,
    Compassion: 60,
    Politeness: 50,
    Volatility: 50,
    Withdrawal: 40,
  },
  "Community-oriented": {
    Openness: 50,
    Intellect: 40,
    Industriousness: 50,
    Orderliness: 50,
    Enthusiasm: 60,
    Assertiveness: 50,
    Compassion: 85,
    Politeness: 80,
    Volatility: 40,
    Withdrawal: 40,
  },

  Professional: {
    Openness: 50,
    Intellect: 60,
    Industriousness: 80,
    Orderliness: 80,
    Enthusiasm: 50,
    Assertiveness: 60,
    Compassion: 50,
    Politeness: 60,
    Volatility: 40,
    Withdrawal: 40,
  },
  "Goal-oriented": {
    Openness: 50,
    Intellect: 50,
    Industriousness: 90,
    Orderliness: 80,
    Enthusiasm: 60,
    Assertiveness: 70,
    Compassion: 40,
    Politeness: 50,
    Volatility: 45,
    Withdrawal: 40,
  },
  Disciplined: {
    Openness: 40,
    Intellect: 50,
    Industriousness: 90,
    Orderliness: 90,
    Enthusiasm: 40,
    Assertiveness: 60,
    Compassion: 40,
    Politeness: 50,
    Volatility: 30,
    Withdrawal: 30,
  },
  Strategic: {
    Openness: 60,
    Intellect: 80,
    Industriousness: 70,
    Orderliness: 80,
    Enthusiasm: 50,
    Assertiveness: 70,
    Compassion: 40,
    Politeness: 50,
    Volatility: 40,
    Withdrawal: 40,
  },

  Mindful: {
    Openness: 60,
    Intellect: 50,
    Industriousness: 40,
    Orderliness: 50,
    Enthusiasm: 40,
    Assertiveness: 40,
    Compassion: 70,
    Politeness: 60,
    Volatility: 20,
    Withdrawal: 30,
  },
  Therapeutic: {
    Openness: 60,
    Intellect: 50,
    Industriousness: 40,
    Orderliness: 50,
    Enthusiasm: 50,
    Assertiveness: 40,
    Compassion: 90,
    Politeness: 80,
    Volatility: 20,
    Withdrawal: 30,
  },
  Emotional: {
    Openness: 50,
    Intellect: 40,
    Industriousness: 40,
    Orderliness: 30,
    Enthusiasm: 60,
    Assertiveness: 40,
    Compassion: 70,
    Politeness: 50,
    Volatility: 80,
    Withdrawal: 70,
  },

}