import {
  Archive,
  Atom,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  Car,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Compass,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  Flag,
  FlaskConical,
  Footprints,
  Gamepad,
  Gauge,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  Megaphone,
  Mic,
  Microscope,
  Mountain,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Plane,
  Sparkle,
  Sprout,
  Sword,
  Target,
  Telescope,
  Tent,
  Theater,
  TrendingUp,
  Trophy,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react-native"

import type {
  ActivityField,
  ActivityType,
} from "@touchgrass/types"

export type { ActivityField, ActivityType }

const ACTIVITY_TYPE_ICONS: Record<ActivityType, LucideIcon> = {
  Creative: Sparkle,
  Artistic: Palette,
  Constructive: Wrench,
  Expressive: Mic,
  Performative: Drama,

  Intellectual: Brain,
  Analytical: Microscope,
  Educational: BookOpen,
  Reflective: Feather,

  Active: Dumbbell,
  Physical: Footprints,
  "Skill-based": Target,
  Competitive: Trophy,

  Adventurous: Compass,
  Outdoorsy: Mountain,
  Exploratory: Telescope,
  Experimental: FlaskConical,

  Social: Users,
  Collaborative: Handshake,
  Leadership: Megaphone,
  "Community-oriented": Sprout,

  Professional: Briefcase,
  "Goal-oriented": Flag,
  Disciplined: Notebook,
  Strategic: Lightbulb,

  Mindful: Leaf,
  Therapeutic: HeartPulse,
  Emotional: Heart,
}

const FIELD_ICONS: Record<ActivityField, LucideIcon> = {
  Music: Guitar,
  Art: Paintbrush,
  Writing: Pen,
  Photography: Camera,
  Film: Film,
  Theater: Drama,
  Dance: Mic,

  Coding: Code,
  Technology: Laptop,
  Science: FlaskConical,
  Astronomy: Telescope,
  Engineering: Wrench,

  Cars: Car,
  Motorcycles: Gauge,
  Aviation: Plane,

  Fitness: Dumbbell,
  Sports: Trophy,
  "Martial Arts": Sword,
  Cycling: Bike,
  Running: Footprints,
  Climbing: Mountain,
  Hiking: Compass,

  Gaming: Gamepad,
  "Board Games": Gamepad,

  Cooking: ChefHat,
  Coffee: Coffee,
  Fashion: Sparkle,

  Travel: Globe,
  Nature: Leaf,
  Camping: Tent,

  Psychology: Brain,
  Philosophy: Feather,
  History: BookOpen,
  Language: Globe,

  Business: Briefcase,
  Finance: TrendingUp,
  Leadership: Megaphone,

  Meditation: Leaf,
  Wellness: Heart,

  Education: GraduationCap,
  Community: Users,
  Volunteering: Handshake,

  DIY: Hammer,
  "Home Design": Home,
  Collecting: Archive,
}

// Fallbacks ensure unknown labels still render a sensible icon rather than nothing.
export function getActivityTypeIcon(type: string): LucideIcon {
  return ACTIVITY_TYPE_ICONS[type as ActivityType] ?? Sparkle
}

export function getFieldIcon(field: string): LucideIcon {
  return FIELD_ICONS[field as ActivityField] ?? Target
}

export const TimeIcon: LucideIcon = Clock

// Re-export the full icon set so callers can extend mappings without re-importing from lucide.
export const Icons = {
  Archive,
  Atom,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  Car,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Compass,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  Flag,
  FlaskConical,
  Footprints,
  Gamepad,
  Gauge,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  Megaphone,
  Mic,
  Microscope,
  Mountain,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Plane,
  Sparkle,
  Sprout,
  Sword,
  Target,
  Telescope,
  Tent,
  Theater,
  TrendingUp,
  Trophy,
  Users,
  Wrench,
}
