import {
  Atom,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Compass,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  Flag,
  FlaskConical,
  Footprints,
  Gamepad,
  Globe,
  Guitar,
  Hammer,
  Handshake,
  Heart,
  HeartPulse,
  Laptop,
  Leaf,
  Lightbulb,
  Megaphone,
  Mic,
  Microscope,
  Mountain,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Sparkle,
  Sprout,
  Sword,
  Target,
  Telescope,
  Theater,
  Trophy,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react-native"

import type {
  ActivityField,
  ActivityType,
} from "@touchgrass/types"

export type { ActivityField, ActivityType }

const ACTIVITY_TYPE_ICONS: Record<ActivityType, LucideIcon> = {
  Creative: Sparkle,
  Artistic: Palette,
  Constructive: Wrench,
  Expressive: Mic,
  Performative: Drama,

  Intellectual: Brain,
  Analytical: Microscope,
  Educational: BookOpen,
  Reflective: Feather,

  Active: Dumbbell,
  Physical: Footprints,
  "Skill-based": Target,
  Competitive: Trophy,

  Adventurous: Compass,
  Outdoorsy: Mountain,
  Exploratory: Telescope,
  Experimental: FlaskConical,

  Social: Users,
  Collaborative: Handshake,
  Leadership: Megaphone,
  "Community-oriented": Sprout,

  Professional: Briefcase,
  "Goal-oriented": Flag,
  Disciplined: Notebook,
  Strategic: Lightbulb,

  Mindful: Leaf,
  Therapeutic: HeartPulse,
  Emotional: Heart,
}

const FIELD_ICONS: Record<ActivityField, LucideIcon> = {
  Music: Guitar,
  "Martial Arts": Sword,
  Literature: BookOpen,
  Cooking: ChefHat,
  Photography: Camera,
  Gaming: Gamepad,
  Fitness: Dumbbell,
  Coding: Code,
  Science: FlaskConical,
  Nature: Leaf,
  Film: Film,
  Theater: Drama,
  "Visual Art": Paintbrush,
  Writing: Pen,
  Dance: Theater,
  Cycling: Bike,
  Hiking: Mountain,
  Travel: Globe,
  Wellness: Heart,
  Astronomy: Telescope,
}

// Fallbacks ensure unknown labels still render a sensible icon rather than nothing.
export function getActivityTypeIcon(type: string): LucideIcon {
  return ACTIVITY_TYPE_ICONS[type as ActivityType] ?? Sparkle
}

export function getFieldIcon(field: string): LucideIcon {
  return FIELD_ICONS[field as ActivityField] ?? Target
}

export const TimeIcon: LucideIcon = Clock

// Re-export the full icon set so callers can extend mappings without re-importing from lucide.
export const Icons = {
  Atom,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Compass,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  Flag,
  FlaskConical,
  Footprints,
  Gamepad,
  Globe,
  Guitar,
  Hammer,
  Handshake,
  Heart,
  HeartPulse,
  Laptop,
  Leaf,
  Lightbulb,
  Megaphone,
  Mic,
  Microscope,
  Mountain,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Sparkle,
  Sprout,
  Sword,
  Target,
  Telescope,
  Theater,
  Trophy,
  Users,
  Wrench,
}
