import {
  Atom,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  FlaskConical,
  Footprints,
  Gamepad,
  Globe,
  Guitar,
  Hammer,
  Heart,
  Laptop,
  Leaf,
  Lightbulb,
  Mic,
  Microscope,
  Mountain,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Sparkle,
  Sprout,
  Sword,
  Target,
  Telescope,
  Theater,
  Trophy,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react-native"

import type {
  ActivityField,
  ActivityType,
} from "@touchgrass/types"

export type { ActivityField, ActivityType }

const ACTIVITY_TYPE_ICONS: Record<ActivityType, LucideIcon> = {
  Constructive: Wrench,
  Active: Dumbbell,
  Artistic: Palette,
  Intellectual: Brain,
  Outdoorsy: Mountain,
  Social: Users,
  Reflective: Feather,
  Creative: Sparkle,
  Adventurous: Footprints,
  Professional: Briefcase,
}

const FIELD_ICONS: Record<ActivityField, LucideIcon> = {
  Music: Guitar,
  "Martial Arts": Sword,
  Literature: BookOpen,
  Cooking: ChefHat,
  Photography: Camera,
  Gaming: Gamepad,
  Fitness: Dumbbell,
  Coding: Code,
  Science: FlaskConical,
  Nature: Leaf,
  Film: Film,
  Theater: Drama,
  "Visual Art": Paintbrush,
  Writing: Pen,
  Dance: Theater,
  Cycling: Bike,
  Hiking: Mountain,
  Travel: Globe,
  Wellness: Heart,
  Astronomy: Telescope,
}

// Fallbacks ensure unknown labels still render a sensible icon rather than nothing.
export function getActivityTypeIcon(type: string): LucideIcon {
  return ACTIVITY_TYPE_ICONS[type as ActivityType] ?? Sparkle
}

export function getFieldIcon(field: string): LucideIcon {
  return FIELD_ICONS[field as ActivityField] ?? Target
}

export const TimeIcon: LucideIcon = Clock

// Re-export the full icon set so callers can extend mappings without re-importing from lucide.
export const Icons = {
  Atom,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  FlaskConical,
  Footprints,
  Gamepad,
  Globe,
  Guitar,
  Hammer,
  Heart,
  Laptop,
  Leaf,
  Lightbulb,
  Mic,
  Microscope,
  Mountain,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Sparkle,
  Sprout,
  Sword,
  Target,
  Telescope,
  Theater,
  Trophy,
  Users,
  Wrench,
}
