import type { ActivityField, ActivityType } from "@touchgrass/types"

export type Recommendation = {
  id: string
  title: string
  imageUrl: string
  type: ActivityType
  field: ActivityField
  estimated_time: string
  related_types?: ActivityType[]
}

export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec_001",
    title: "Build a Guitar Pedalboard",
    imageUrl: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&q=80",
    type: "Constructive",
    field: "Music",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_002",
    title: "Join a Beginner Boxing Class",
    imageUrl: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80",
    type: "Active",
    field: "Martial Arts",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_003",
    title: "Write a Short Horror Screenplay",
    imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    type: "Artistic",
    field: "Literature",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_004",
    title: "Journal While Listening to Jazz",
    imageUrl: "https://picsum.photos/seed/rec_004/800/600",
    type: "Reflective",
    field: "Music",
    estimated_time: "30 minutes",
    related_types: [],
  },
  {
    id: "rec_005",
    title: "Study Music Theory Basics",
    imageUrl: "https://picsum.photos/seed/rec_005/800/600",
    type: "Intellectual",
    field: "Music",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_006",
    title: "Compose a 1-Minute Song",
    imageUrl: "https://picsum.photos/seed/rec_006/800/600",
    type: "Creative",
    field: "Music",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_007",
    title: "Host a Vinyl Listening Night",
    imageUrl: "https://picsum.photos/seed/rec_007/800/600",
    type: "Social",
    field: "Music",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_008",
    title: "Build a Home Heavy Bag Stand",
    imageUrl: "https://picsum.photos/seed/rec_008/800/600",
    type: "Constructive",
    field: "Martial Arts",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_009",
    title: "Learn Tai Chi Basics",
    imageUrl: "https://picsum.photos/seed/rec_009/800/600",
    type: "Reflective",
    field: "Martial Arts",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_010",
    title: "Read a Bruce Lee Biography",
    imageUrl: "https://picsum.photos/seed/rec_010/800/600",
    type: "Intellectual",
    field: "Martial Arts",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_011",
    title: "Plan a Martial Arts Training Trip",
    imageUrl: "https://picsum.photos/seed/rec_011/800/600",
    type: "Adventurous",
    field: "Martial Arts",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_012",
    title: "Start a 30-Day Reading Challenge",
    imageUrl: "https://picsum.photos/seed/rec_012/800/600",
    type: "Reflective",
    field: "Literature",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_013",
    title: "Join a Local Book Club",
    imageUrl: "https://picsum.photos/seed/rec_013/800/600",
    type: "Social",
    field: "Literature",
    estimated_time: "Ongoing",
    related_types: [],
  },
  {
    id: "rec_014",
    title: "Submit a Story to a Literary Magazine",
    imageUrl: "https://picsum.photos/seed/rec_014/800/600",
    type: "Professional",
    field: "Literature",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_015",
    title: "Analyze a Classic Novel Chapter by Chapter",
    imageUrl: "https://picsum.photos/seed/rec_015/800/600",
    type: "Intellectual",
    field: "Literature",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_016",
    title: "Bake Sourdough From a Live Starter",
    imageUrl: "https://picsum.photos/seed/rec_016/800/600",
    type: "Constructive",
    field: "Cooking",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_017",
    title: "Host a Three-Course Dinner Party",
    imageUrl: "https://picsum.photos/seed/rec_017/800/600",
    type: "Social",
    field: "Cooking",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_018",
    title: "Develop a Personal Cookbook",
    imageUrl: "https://picsum.photos/seed/rec_018/800/600",
    type: "Creative",
    field: "Cooking",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_019",
    title: "Cook One Region's Cuisine for a Week",
    imageUrl: "https://picsum.photos/seed/rec_019/800/600",
    type: "Adventurous",
    field: "Cooking",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_020",
    title: "Pitch a Pop-Up Restaurant Concept",
    imageUrl: "https://picsum.photos/seed/rec_020/800/600",
    type: "Professional",
    field: "Cooking",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_021",
    title: "Shoot a Golden Hour Walk",
    imageUrl: "https://picsum.photos/seed/rec_021/800/600",
    type: "Reflective",
    field: "Photography",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_022",
    title: "Build a Working Pinhole Camera",
    imageUrl: "https://picsum.photos/seed/rec_022/800/600",
    type: "Constructive",
    field: "Photography",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_023",
    title: "Create a 12-Page Photo Zine",
    imageUrl: "https://picsum.photos/seed/rec_023/800/600",
    type: "Artistic",
    field: "Photography",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_024",
    title: "Lead a Saturday Photowalk",
    imageUrl: "https://picsum.photos/seed/rec_024/800/600",
    type: "Social",
    field: "Photography",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_025",
    title: "Capture Wildlife in a State Park",
    imageUrl: "https://picsum.photos/seed/rec_025/800/600",
    type: "Outdoorsy",
    field: "Photography",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_026",
    title: "Run a Tabletop RPG One-Shot",
    imageUrl: "https://picsum.photos/seed/rec_026/800/600",
    type: "Social",
    field: "Gaming",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_027",
    title: "Build a Custom Mechanical Keyboard",
    imageUrl: "https://picsum.photos/seed/rec_027/800/600",
    type: "Constructive",
    field: "Gaming",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_028",
    title: "Design a Board Game Prototype",
    imageUrl: "https://picsum.photos/seed/rec_028/800/600",
    type: "Creative",
    field: "Gaming",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_029",
    title: "Stream Your First Twitch Session",
    imageUrl: "https://picsum.photos/seed/rec_029/800/600",
    type: "Professional",
    field: "Gaming",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_030",
    title: "Beat a Notoriously Difficult RPG",
    imageUrl: "https://picsum.photos/seed/rec_030/800/600",
    type: "Adventurous",
    field: "Gaming",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_031",
    title: "Try a 30-Day Push-Up Challenge",
    imageUrl: "https://picsum.photos/seed/rec_031/800/600",
    type: "Active",
    field: "Fitness",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_032",
    title: "Build a Garage Gym Setup",
    imageUrl: "https://picsum.photos/seed/rec_032/800/600",
    type: "Constructive",
    field: "Fitness",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_033",
    title: "Map a Park Workout Loop",
    imageUrl: "https://picsum.photos/seed/rec_033/800/600",
    type: "Outdoorsy",
    field: "Fitness",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_034",
    title: "Sign Up for Your First 5K",
    imageUrl: "https://picsum.photos/seed/rec_034/800/600",
    type: "Adventurous",
    field: "Fitness",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_035",
    title: "Get Personal Trainer Certified",
    imageUrl: "https://picsum.photos/seed/rec_035/800/600",
    type: "Professional",
    field: "Fitness",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_036",
    title: "Build a Personal Site From Scratch",
    imageUrl: "https://picsum.photos/seed/rec_036/800/600",
    type: "Constructive",
    field: "Coding",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_037",
    title: "Read The Pragmatic Programmer",
    imageUrl: "https://picsum.photos/seed/rec_037/800/600",
    type: "Intellectual",
    field: "Coding",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_038",
    title: "Join a Local Hack Night",
    imageUrl: "https://picsum.photos/seed/rec_038/800/600",
    type: "Social",
    field: "Coding",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_039",
    title: "Make Generative Art With p5.js",
    imageUrl: "https://picsum.photos/seed/rec_039/800/600",
    type: "Creative",
    field: "Coding",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_040",
    title: "Contribute Your First Open Source PR",
    imageUrl: "https://picsum.photos/seed/rec_040/800/600",
    type: "Professional",
    field: "Coding",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_041",
    title: "Run a Kitchen Chemistry Experiment",
    imageUrl: "https://picsum.photos/seed/rec_041/800/600",
    type: "Constructive",
    field: "Science",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_042",
    title: "Read Cosmos by Carl Sagan",
    imageUrl: "https://picsum.photos/seed/rec_042/800/600",
    type: "Reflective",
    field: "Science",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_043",
    title: "Track a Citizen Science Project",
    imageUrl: "https://picsum.photos/seed/rec_043/800/600",
    type: "Intellectual",
    field: "Science",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_044",
    title: "Hike to a Geological Formation",
    imageUrl: "https://picsum.photos/seed/rec_044/800/600",
    type: "Outdoorsy",
    field: "Science",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_045",
    title: "Apply to a Lab Volunteer Program",
    imageUrl: "https://picsum.photos/seed/rec_045/800/600",
    type: "Professional",
    field: "Science",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_046",
    title: "Start an Indoor Herb Garden",
    imageUrl: "https://picsum.photos/seed/rec_046/800/600",
    type: "Constructive",
    field: "Nature",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_047",
    title: "Spend an Hour Forest Bathing",
    imageUrl: "https://picsum.photos/seed/rec_047/800/600",
    type: "Reflective",
    field: "Nature",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_048",
    title: "Identify Ten Local Plant Species",
    imageUrl: "https://picsum.photos/seed/rec_048/800/600",
    type: "Intellectual",
    field: "Nature",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_049",
    title: "Volunteer for a Trail Cleanup",
    imageUrl: "https://picsum.photos/seed/rec_049/800/600",
    type: "Social",
    field: "Nature",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_050",
    title: "Camp Solo for a Single Night",
    imageUrl: "https://picsum.photos/seed/rec_050/800/600",
    type: "Adventurous",
    field: "Nature",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_051",
    title: "Shoot a 60-Second Short Film",
    imageUrl: "https://picsum.photos/seed/rec_051/800/600",
    type: "Creative",
    field: "Film",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_052",
    title: "Watch a Director's Full Filmography",
    imageUrl: "https://picsum.photos/seed/rec_052/800/600",
    type: "Intellectual",
    field: "Film",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_053",
    title: "Host a Themed Film Night",
    imageUrl: "https://picsum.photos/seed/rec_053/800/600",
    type: "Social",
    field: "Film",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_054",
    title: "Pitch a TV Pilot Logline",
    imageUrl: "https://picsum.photos/seed/rec_054/800/600",
    type: "Professional",
    field: "Film",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_055",
    title: "Reflect on Your Five Favorite Films",
    imageUrl: "https://picsum.photos/seed/rec_055/800/600",
    type: "Reflective",
    field: "Film",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_056",
    title: "Audition for Community Theater",
    imageUrl: "https://picsum.photos/seed/rec_056/800/600",
    type: "Active",
    field: "Theater",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_057",
    title: "Build a Set Piece for a Production",
    imageUrl: "https://picsum.photos/seed/rec_057/800/600",
    type: "Constructive",
    field: "Theater",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_058",
    title: "Write a 10-Minute Play",
    imageUrl: "https://picsum.photos/seed/rec_058/800/600",
    type: "Artistic",
    field: "Theater",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_059",
    title: "Run an Improv Night With Friends",
    imageUrl: "https://picsum.photos/seed/rec_059/800/600",
    type: "Social",
    field: "Theater",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_060",
    title: "Direct a Staged Reading",
    imageUrl: "https://picsum.photos/seed/rec_060/800/600",
    type: "Professional",
    field: "Theater",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_061",
    title: "Paint a Self-Portrait",
    imageUrl: "https://picsum.photos/seed/rec_061/800/600",
    type: "Artistic",
    field: "Visual Art",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_062",
    title: "Take a Pottery Wheel Class",
    imageUrl: "https://picsum.photos/seed/rec_062/800/600",
    type: "Constructive",
    field: "Visual Art",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_063",
    title: "Sketch in a Public Park",
    imageUrl: "https://picsum.photos/seed/rec_063/800/600",
    type: "Outdoorsy",
    field: "Visual Art",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_064",
    title: "Curate a Gallery Wall in Your Home",
    imageUrl: "https://picsum.photos/seed/rec_064/800/600",
    type: "Creative",
    field: "Visual Art",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_065",
    title: "Sell a Piece at a Local Market",
    imageUrl: "https://picsum.photos/seed/rec_065/800/600",
    type: "Professional",
    field: "Visual Art",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_066",
    title: "Draft a Personal Essay",
    imageUrl: "https://picsum.photos/seed/rec_066/800/600",
    type: "Reflective",
    field: "Writing",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_067",
    title: "Co-Write a Story With a Friend",
    imageUrl: "https://picsum.photos/seed/rec_067/800/600",
    type: "Social",
    field: "Writing",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_068",
    title: "Try Stream-of-Consciousness Daily",
    imageUrl: "https://picsum.photos/seed/rec_068/800/600",
    type: "Creative",
    field: "Writing",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_069",
    title: "Pitch a Magazine Feature Article",
    imageUrl: "https://picsum.photos/seed/rec_069/800/600",
    type: "Professional",
    field: "Writing",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_070",
    title: "Travel for Writing Inspiration",
    imageUrl: "https://picsum.photos/seed/rec_070/800/600",
    type: "Adventurous",
    field: "Writing",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_071",
    title: "Take a Beginner Salsa Class",
    imageUrl: "https://picsum.photos/seed/rec_071/800/600",
    type: "Active",
    field: "Dance",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_072",
    title: "Learn a TikTok Choreography",
    imageUrl: "https://picsum.photos/seed/rec_072/800/600",
    type: "Creative",
    field: "Dance",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_073",
    title: "Attend a Friday Night Dance Social",
    imageUrl: "https://picsum.photos/seed/rec_073/800/600",
    type: "Social",
    field: "Dance",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_074",
    title: "Choreograph a 30-Second Routine",
    imageUrl: "https://picsum.photos/seed/rec_074/800/600",
    type: "Artistic",
    field: "Dance",
    estimated_time: "A few hours",
    related_types: [],
  },
  {
    id: "rec_075",
    title: "Study the History of Modern Dance",
    imageUrl: "https://picsum.photos/seed/rec_075/800/600",
    type: "Intellectual",
    field: "Dance",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_076",
    title: "Ride a New 20-Mile Loop",
    imageUrl: "https://picsum.photos/seed/rec_076/800/600",
    type: "Adventurous",
    field: "Cycling",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_077",
    title: "Build Up a Used Bike Frame",
    imageUrl: "https://picsum.photos/seed/rec_077/800/600",
    type: "Constructive",
    field: "Cycling",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_078",
    title: "Join a Sunday Group Ride",
    imageUrl: "https://picsum.photos/seed/rec_078/800/600",
    type: "Social",
    field: "Cycling",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_079",
    title: "Race Your First Local Crit",
    imageUrl: "https://picsum.photos/seed/rec_079/800/600",
    type: "Active",
    field: "Cycling",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_080",
    title: "Cycle Through a National Park",
    imageUrl: "https://picsum.photos/seed/rec_080/800/600",
    type: "Outdoorsy",
    field: "Cycling",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_081",
    title: "Hike a Sunrise Summit",
    imageUrl: "https://picsum.photos/seed/rec_081/800/600",
    type: "Adventurous",
    field: "Hiking",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_082",
    title: "Plan a Three-Day Backpacking Trip",
    imageUrl: "https://picsum.photos/seed/rec_082/800/600",
    type: "Outdoorsy",
    field: "Hiking",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_083",
    title: "Lead a Friend on Their First Hike",
    imageUrl: "https://picsum.photos/seed/rec_083/800/600",
    type: "Social",
    field: "Hiking",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_084",
    title: "Photograph a Trail in a Series",
    imageUrl: "https://picsum.photos/seed/rec_084/800/600",
    type: "Artistic",
    field: "Hiking",
    estimated_time: "An afternoon",
    related_types: [],
  },
  {
    id: "rec_085",
    title: "Journal at a Mountain Overlook",
    imageUrl: "https://picsum.photos/seed/rec_085/800/600",
    type: "Reflective",
    field: "Hiking",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_086",
    title: "Plan a Weekend Solo Trip",
    imageUrl: "https://picsum.photos/seed/rec_086/800/600",
    type: "Adventurous",
    field: "Travel",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_087",
    title: "Build a Travel Photo Book",
    imageUrl: "https://picsum.photos/seed/rec_087/800/600",
    type: "Creative",
    field: "Travel",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_088",
    title: "Learn 50 Words in a New Language",
    imageUrl: "https://picsum.photos/seed/rec_088/800/600",
    type: "Intellectual",
    field: "Travel",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_089",
    title: "Host a Couchsurfer for a Weekend",
    imageUrl: "https://picsum.photos/seed/rec_089/800/600",
    type: "Social",
    field: "Travel",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_090",
    title: "Apply to Be a Travel Writer",
    imageUrl: "https://picsum.photos/seed/rec_090/800/600",
    type: "Professional",
    field: "Travel",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_091",
    title: "Run a 7-Day Meditation Streak",
    imageUrl: "https://picsum.photos/seed/rec_091/800/600",
    type: "Reflective",
    field: "Wellness",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_092",
    title: "Build a Morning Routine",
    imageUrl: "https://picsum.photos/seed/rec_092/800/600",
    type: "Constructive",
    field: "Wellness",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_093",
    title: "Take a Yin Yoga Class",
    imageUrl: "https://picsum.photos/seed/rec_093/800/600",
    type: "Active",
    field: "Wellness",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_094",
    title: "Track Your Sleep for Two Weeks",
    imageUrl: "https://picsum.photos/seed/rec_094/800/600",
    type: "Intellectual",
    field: "Wellness",
    estimated_time: "A week",
    related_types: [],
  },
  {
    id: "rec_095",
    title: "Become a Certified Yoga Teacher",
    imageUrl: "https://picsum.photos/seed/rec_095/800/600",
    type: "Professional",
    field: "Wellness",
    estimated_time: "A month",
    related_types: [],
  },
  {
    id: "rec_096",
    title: "Stargaze in a Dark Sky Park",
    imageUrl: "https://picsum.photos/seed/rec_096/800/600",
    type: "Outdoorsy",
    field: "Astronomy",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_097",
    title: "Build a Backyard Telescope Mount",
    imageUrl: "https://picsum.photos/seed/rec_097/800/600",
    type: "Constructive",
    field: "Astronomy",
    estimated_time: "A weekend",
    related_types: [],
  },
  {
    id: "rec_098",
    title: "Reflect on the Cosmos Under the Night Sky",
    imageUrl: "https://picsum.photos/seed/rec_098/800/600",
    type: "Reflective",
    field: "Astronomy",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_099",
    title: "Track an Overnight Meteor Shower",
    imageUrl: "https://picsum.photos/seed/rec_099/800/600",
    type: "Adventurous",
    field: "Astronomy",
    estimated_time: "1 hour",
    related_types: [],
  },
  {
    id: "rec_100",
    title: "Photograph the Milky Way",
    imageUrl: "https://picsum.photos/seed/rec_100/800/600",
    type: "Artistic",
    field: "Astronomy",
    estimated_time: "An afternoon",
    related_types: [],
  },
]
